server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/es_panda?useSSL=false
    username: root
    password: lcz19930316
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: leechenze
    password: 930316
    virtual-host: / # leechenze这个用户的虚拟主机（/）
logging:
  level:
    com.lee: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lee.hotel.pojo
