server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: lcz19930316
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: cn.lee.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.lee: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS