logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 172.16.168.130:27001
        - 172.16.168.130:27002
        - 172.16.168.130:27003